WOW/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.conf.urls import url

from home.views import home_view, about_view, contact_view
from accounts.views import login_page, register_page

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_view, name="home"),
    url(r'^about/', about_view, name="about"),
    url(r'^contact/', contact_view, name="contact"),
    url(r'^login/', login_page, name="login"),
    url(r'^logout', LogoutView.as_view(), name="logout"),
    url(r'^registration/', register_page, name="register"),
    url(r'^events/', include(('events.urls', 'events'), namespace='events')),
    url(r'^meetups/', include(('meetups.urls', 'meetups'), namespace='meetups')),
    url(r'^jobs/', include(('jobs.urls', 'jobs'), namespace='jobs')),
    url(r'^communities/', include(('communities.urls', 'communities'), namespace='communities')),
    url(r'^search/', include(('search.urls', 'search'), namespace='search')),

    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('admindash/',include('admindash.urls')),


]
urlpatterns += staticfiles_urlpatterns()


#

meetups/urls.py
from django.conf.urls import url
from .views import meetups_view, meetups_detail_view, add_meetups

urlpatterns = [
    url(r'^$', meetups_view, name='list'),
    url(r'^add/$', add_meetups, name='add'),
    url(r'^meetup/(?P<meetup_id>[\w-]+)/$', meetups_detail_view, name='detail'),
]

meetups/models.py
from django.db import models


class Meetup(models.Model):
    title = models.CharField(max_length=120)
    address = models.CharField(max_length=1200)
    location = models.CharField(max_length=120)
    description = models.TextField(max_length=3000)
    date = models.DateField()
    time = models.TimeField()
    attendance = models.IntegerField(default=0, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    count = models.IntegerField(default=0)


    def __str__(self):
        return self.title

meetups/forms.py
from django import forms
from .models import Meetup


class AddMeetup(forms.ModelForm):
    class Meta:
        model = Meetup
        exclude = {'attendence'}
        fields  = [
            'title',
            'address',
            'location',
            'description',
            'date',
            'time'
        ]
        widgets = {
            'date': forms.DateInput(attrs={'class': 'datepicker'}),
        }

meetups/views.py
from django.shortcuts import render, redirect
from django.db.models import F

from .models import Meetup
from .forms import AddMeetup
from events.models import Event

def meetups_view(request):
    meetups = Meetup.objects.all()
    # enrolled = Enrolled.objects.all()

    context = {
        "meetups": meetups,
        "title": "Meetups",
    }
    return render(request, "meetups/meetups.html", context)


def meetups_detail_view(request, meetup_id):
    meetup = Meetup.objects.get(id=meetup_id)

    context = {
        "title": meetup.title,
        "meetup": meetup,
    }
    if request.method == "POST":
        print("YOYO")
        events = Event.objects.create(user = request.user,meetup = meetup )
        meetup_new = Meetup.objects.get(id=meetup_id)

        meetup_new.count = F('count') + 1
        meetup_new.save()
        return render(request, "meetups/meetups.html", context)
    else:
        return render(request, "meetups/detail.html", context)

def add_meetups(request):
    if request.user.is_authenticated:
        # form = AddMeetup()
        context = {
            "title": "Add Meetup",
            # "form": form,
        }
        if request.method == "POST":
            title = request.POST['title']
            address = request.POST['address']
            location = request.POST['location']
            description = request.POST['description']
            date = request.POST['date']
            time = request.POST['time']

            meetup = Meetup.objects.create(title=title ,address=address , location=location ,description=description,date=date,time=time)
            meetup.save()
        return render(request, "meetups/add.html", context)
    else:
        return redirect('/login/')

templates/meetups/add.html
 {% comment %} {% extends "WOW/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <script>
        $(function () {
            $(".datepicker").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "1900:2012",
            });
        });
    </script>
    Add Event

    <form action="" method="POST">{% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit">Submit</button>
    </form>


{% endblock %}     {% endcomment %}






{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Contact V1</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"> {% endcomment %}

	{% comment %} <link rel="stylesheet" type="text/css" href="css/main.css"> {% endcomment %}
	    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="//malihu.github.io/custom-scrollbar/jquery.mCustomScrollbar.min.css">

    <!-- using local links -->
    <!-- <link rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../node_modules/@fortawesome/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="../node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css"> -->

    <link rel="stylesheet" href="{% static 'css/33.css' %}">
    <link rel="stylesheet" href="{% static 'css/34.css' %}">
    <link rel="shortcut icon" type="image/png" href="img/favicon.png" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <!--    <link href="css/bootstrap.min.css" rel="stylesheet">-->
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/35.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/36.css' %}" rel="stylesheet">
    <link href="{% static 'css/37.css' %}" rel="stylesheet">

    <link href="{% static 'css/38.css' %}" rel="stylesheet">

    <link href="{% static 'css/39.css' %}" rel="stylesheet">
    <link href="{% static 'css/40.css' %}" rel="stylesheet">
    <link href="{% static 'css/41.css' %}" rel="stylesheet">
    <link href="{% static 'css/42.css' %}" rel="stylesheet">
    <link href="{% static 'css/43.css' %}" rel="stylesheet">



    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }

        @media (max-width: 740px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
 nav{

  background: -webkit-linear-gradient(0deg, #bfacff 0%, #795fff 100%) !important;


        }


.navbar-light .navbar-nav .nav-link {
  color:#fff;


        }

        .navbar.navbar-light .breadcrumb .nav-item .nav-link, .navbar.navbar-light .navbar-nav .nav-item .nav-link {
              color:#fff;
        }



        .contact1 {

    background: -webkit-linear-gradient(left, #fff, #fff) !important;
        }
    </style>
<!--===============================================================================================-->


<script>
        $(function () {
            $(".datepicker").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "1900:2012",
            });
        });
</script>


</head>
<body>
	<div class="row">
        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar navvy">
            <div class="container">

                <!-- Brand -->
                <a class="navbar-brand waves-effect" href="/">
                    <strong class="blue-text">WOW</strong>
                </a>

                <!-- Collapse -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Links -->

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Left -->
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">

                    </li>
                    <a class="nav-link waves-effect" href="{% url 'communities:list' %}">COMMUNITIES

                    </a>
                    <a class="nav-link waves-effect" href="{% url 'jobs:list' %}">JOBS
                        <span class="sr-only">(current)</span>
                    </a>
                    <a class="nav-link waves-effect" href="{% url 'meetups:list' %}">MEETUPS
                        <span class="sr-only">(current)</span>
                    </a>
                    <a class="nav-link waves-effect" href="{% url 'events:list' %}">EVENTS
                        <span class="sr-only">(current)</span>
                    </a>
                    <a class="nav-link waves-effect" href="{% url 'about' %}">ABOUT
                        <span class="sr-only">(current)</span>
                    </a>
                    <a class="nav-link waves-effect" href="{% url 'contact' %}">CONTACTS
                        <span class="sr-only">(current)</span>
                    </a>


                </ul>

                    <!-- Right -->
                    <ul class="navbar-nav nav-flex-icons">

                        {% if request.user.is_authenticated %}

                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'logout' %}">
                                <span class="clearfix d-none d-sm-inline-block"> Welcome <b>{{ request.user.username }}</b> </span>
                            </a>
                        </li>
                        {% else %}

                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'login' %}">
                                <span class="clearfix d-none d-sm-inline-block"> Sign In </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link waves-effect" href="{% url 'register' %}">
                                <span class="clearfix d-none d-sm-inline-block"> Signup </span>
                            </a>
                        </li>
                               {% endif %}
                    </ul>
                </div>





            </div>
        </nav>
    </div>

	<div class="contact1">
		<div class="container-contact1">
			{% comment %} <div class="contact1-pic js-tilt" data-tilt>

		    </div> {% endcomment %}

			<form class="contact1-form validate-form jayit" method="POST">

		{% csrf_token %}
				<span class="contact1-form-title">
				ADD EVENT
				</span>

				<div class="wrap-input1 validate-input" >
				<input type="text" name="title" maxlength="120" class="input1" required="" id="id_title" placeholder="Title...">
				<span class="shadow-input1"></span>
				</div>

				<div class="wrap-input1 validate-input" data-validate = "Name is required">
				<input type="text" name="address" maxlength="1200" class="input1" required="" id="id_address" placeholder="Address...">
				<span class="shadow-input1"></span>
				</div>



				<div class="wrap-input1 validate-input" data-validate = "Subject is required">
				<input type="text" name="location" maxlength="120" class="input1" required="" id="id_location" placeholder="Location...">
				<span class="shadow-input1"></span>
				</div>

				<div class="wrap-input1 validate-input" data-validate = "Message is required">
					<textarea class="input1" name="description" placeholder="Message"></textarea>
					<span class="shadow-input1"></span>
				</div>


				<div class="wrap-input1 validate-input" data-validate = "Subject is required">
				<input type="text" name="date" class="datepicker input1" required="" id="id_date" placeholder="Date...">
				<span class="shadow-input1"></span>
				</div>

				<div class="wrap-input1 validate-input" data-validate = "Subject is required">
				<input type="text" name="time" class="timeinput input1" required="" id="id_time" placeholder="Time...">
				<span class="shadow-input1"></span>
				</div>


				<div class="container-contact1-form-btn">
					<button class="contact1-form-btn" type="submit" >
						<span>
							Submit
							<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
						</span>
					</button>
				</div>
			</form>
		</div>
	</div>




<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/tilt/tilt.jquery.min.js"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>